### ISSUE TITLE
Process completed with exit code 2.

### ISSUE THREAD

**Issue by louwjlabuschagne** [embano1/wip#3]
Has something changed on github workflows causing this to fail with the following?

```log
Run embano1/wip@v1
Run set -ex
+ shopt -s nocasematch
/home/runner/work/_temp/c13378fb-cc02-4414-ace5-05e4179fa6dc.sh: line 7: conditional binary operator expected
Error: Process completed with exit code 2.
```

**Comment by embano1** [comment]
Oh, never though someone else than me is using this one :) Bash can be tricky and I haven't done extensive unit testing for this one. It's not failing for me but seems you have some input characters in your workflow (PR?) which causes this. Are you using this in a PR run? What's the title passed?

**Comment by embano1** [comment]
Closing as inactive. Let me know if you're still seeing it and I'll reopen.
