### ISSUE TITLE
Security Contact

### ISSUE THREAD

**Issue by R3x** [embano1/wip#4]
Hello,

I would like to report a security vulnerability in private, I was not able to find a security contact for this repository and there is no security policy as well. What would be a good contact to reach out to?

**Comment by embano1** [comment]
Thx for reaching out. I should archive this repo as it’s not maintained anymore. Do you want to file a PR to fix the security issue you detected?

**Comment by R3x** [comment]
@embano1 it's a critical issue that might lead to complications for anyone using this action. If you enable private vulnerability reporting I can tell you the fix!

**Comment by embano1** [comment]
Done.

Please note that once the fix is out (PR/commit), everyone will be able to see the (fixed) security issue and I cannot force dependents to immediately/atomically update their workflows.

**Comment by embano1** [comment]
Thx again for your help on this one!
